### ISSUE TITLE
Question: How do you manage and install custom plugins?

### ISSUE THREAD

**Issue by ataki** [juniorsysadmin/puppet-kong#14]
Hi, we're using puppet-kong to manage our kong deployment, and were having issues loading plugin source code written in lua into kong.

I saw that there was a `custom_plugin` configuration in puppet to do this. Where would I place the source code of my repo? I've tried setting a `lua_path` with the source code but restarting the kong service doesn't seem to pick it up.

**Comment by ataki** [comment]
thanks for triaging. We were able to successfully create a plugin by following the template (https://github.com/Mashape/kong-plugin) on creating a standard plugin and making via luarocks. The `lua_path` and `custom_plugin` keywords work as expected.

**Comment by juniorsysadmin** [comment]
I was going to answer earlier but then I seemed to recall that the plugin path might have changed in recent versions.
