### ISSUE TITLE
Purged to '0.8.3' on every puppet run

### ISSUE THREAD

**Issue by davideagle** [juniorsysadmin/puppet-kong#6]
I'm experiencing that the module tries to install the package on every puppet run

Ubuntu 14.04
puppet-kong 0.3.0

Notice: /Stage[main]/Kong::Install/Package[kong:]/ensure: ensure changed 'purged' to '0.8.3'
Notice: /Stage[main]/Kong::Service/Service[kong]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Kong::Service/Service[kong]: Unscheduling refresh on Service[kong]

**Comment by davideagle** [comment]
I've created a pull request to address this issue

**Comment by juniorsysadmin** [comment]
#8

**Comment by juniorsysadmin** [comment]
I believe should now be fixed by #10
